config/routes.rb
Rails.application.routes.draw do
  resources :showings, except: [:new, :create, :edit, :update, :destroy]
  resources :bookings, except: [:show, :edit, :update, :index]
  resources :films, except: [:new, :create, :edit, :update, :destroy]
  resources :venues, only: [:index]
  root 'home#index'
  get 'film', to: "films#index"
  get 'showings', to: 'showings#index'
  get 'mybookings', to: 'my_bookings#index'
  get 'mybookings/find', to: "my_bookings#find"
  post 'book', to: "bookings#parseAjax"
  get 'contact', to: "home#contact"
  post 'request_contact', to: 'home#request_contact'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/showing.rb
class Showing < ApplicationRecord
  # Showing has exactly one film and one venue
  belongs_to :film
  belongs_to :venue
  # Both may not be null
  validates :time, presence: true
  validates :price, presence: true
end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  before_action :set_showing, only: [:show, :edit, :update, :destroy]

  # GET /showings
  # GET /showings.json
  # Method to show all the showings for a particular film and venue.
  def index 
    # validation to ensure that the film and venue parameters are present.
    if params[:film].present? && params[:venue].present?
      # validation to both input parameters are valid
      if Film.exists?(params[:film]) && Venue.exists?(params[:venue])
        @film = Film.find(params[:film])
        @venue = Venue.find(params[:venue])
        # Get all shoings for particular venue and film
        @venueShowings = Showing.where(film: params[:film],venue_id: @venue.id).order(:time)
      else #Redirect with notice if not valid
        redirect_to films_url
        flash[:alert] = t("showings.index.no_param")
      end 
    else # Redirect to root with notice if not present
      redirect_to root_url
      flash[:alert] = t("showings.index.bad_param")
    end 
  end
  
  # GET /showing/1
  def show 
    @film = params[:film]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showing
      # Validation to ensure showing has a showinf id parameter
      if Showing.exists?(id: params[:id])
        @showing = Showing.find(params[:id])
      else
        # Redirect if invalid with notice
        redirect_to showings_path
        flash[:alert] = t('films.film.no_film')
      end
      
    end


end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/views/showings/index.html.erb
<%# Wrapper to ensure that the website isnt full viewport width on larger displays %>
<div class="wrapper-inner p-4">
  <div class="showing-show row py-4 my-4">
    <img class="expand-img glow-shadow m-3" src="<%= @venue.image_url %>" />
    <h1 class='display-4 m-3'><%= @venue.name %></h1>

      <%# List showing data about each showing %>
      <ul class="meta-list showing-meta m-3">
      <li class="text-muted"><%= t('showings.index.location') %></li>
      <li><%= @venue.location %></li>
      <hr class="no-pointer">
      <li class="text-muted"><%= t('venues.index.cap') %></li>
      <li><%= @venue.rows * @venue.seats_per_row %><%= t('venues.index.cap2') %></li>
      <hr class="no-pointer">
      <li class="text-muted"><%= t('showings.index.select') %></li>
      <li><%= @film.title %></li>
      <hr class="no-pointer">
      <li class="text-muted mb-2" ><%= t('showings.index.times') %></li>
      
      <%# user selectable buttons showing the specific showing times for the venue -film combo  %>
      <div class = "showings-buttons-wrapper">
        <% @venueShowings.each do |showing| %>     
          <button id="showing-<%= showing.id%>" class = "btn btn-lg btn-outline-warning badge-pill m-2 glow-shadow" onclick="toggleExpand(true,this.id,'showing-expand')"><%= showing.time.strftime('%H:%M') %></button>
          <div id="showing-expand-<%= showing.id %>" class="grid-expand">
            
            <%# Expanded showing infomation, only shown for each specifc showing time %>
            <div class="expand-overlay2" id="expand-overlay-<%= showing.id %>" onclick="toggleExpand(false,this.id,'showing-expand')"></div>
            <div class="expand-content2 p-2" style="max-width: 300px; text-align: left">

              <%# Showing info %>
              <div class="showing-popout-header">
                <p class='mb-0'><%= t('showings.index.showing') %></p> 
                <span class="btn btn-warning badge-pill mx-2 no-pointer"><%= showing.time.strftime('%H:%M') %><span>
              </div>
              <hr class="no-pointer">
              <%# Button to expand the mini seat grid partial  %>
              <div class="showing-popout-actions">
                <p class="mb-0 text-muted"><%= t('bookings.form.cinemaOverview') %></p>
                <button type="button" id="seat-grid-toggle-<%= showing.id%>" class="btn btn-sm btn-outline-secondary" onclick="overviewToggle(this.id)">Expand Overview</button>
              </div>
              <hr class="no-pointer">
              <div id="seat-grid-mini-<%= showing.id%>" class="seat-grid-mini my-2" style="max-height: 0px">
                <%= render 'shared/seat_grid', booking: @booking, showing: showing %>
              </div> 
              <%= button_to t('showings.index.select'),  new_booking_path, method: :get, params: { showing: showing }, class: "btn btn-block btn-outline-warning glow-shadow", id: "badge-#{showing.id}"%>
              <button id="showing-cell-close-<%= showing.id %>"class="expand-close btn btn-sm btn-outline-secondary my-2" onclick="toggleExpand(false,this.id,'showing-expand')"><%= t('films.film.close')%></button> 
            </div>      
          </div>                                 
        <% end %> 
      </div>
      <%= button_to t('global.back'),  venues_path, method: :get, params: { film: @film }, class: "mt-2 expand-close btn btn-sm btn-outline-secondary"%>
    </ul>
</div>  



                        

                      