config/routes.rb
Rails.application.routes.draw do
  resources :showings, except: [:new, :create, :edit, :update, :destroy]
  resources :bookings, except: [:show, :edit, :update, :index]
  resources :films, except: [:new, :create, :edit, :update, :destroy]
  resources :venues, only: [:index]
  root 'home#index'
  get 'film', to: "films#index"
  get 'showings', to: 'showings#index'
  get 'mybookings', to: 'my_bookings#index'
  get 'mybookings/find', to: "my_bookings#find"
  post 'book', to: "bookings#parseAjax"
  get 'contact', to: "home#contact"
  post 'request_contact', to: 'home#request_contact'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #Default index method 
  # GET /
  def index
  end

  # GET /contact
  # Method to show contact view
  def contact
  end

  # Method to handle contact fomr submit
  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    
    if email.blank? #If email has no content, flash error alert
      flash[:alert] = t('home.mailer.no_email')
    
    else # Send an email #Flash a sent notice 
      flash[:notice] = t('home.mailer.email_sent')
    end
    ContactMailer.contact_email(email,name,telephone,message).deliver_now
    redirect_to root_path #Redirect to root 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<%# Wrapper to ensure that the website isnt full viewport width on larger displays %>
<div class="wrapper-inner px-4">
  <div class="heading mx-2 mb-4" style="text-align: center">
    <h1 class="title display-4"><%= t('home.contact.title') %></h1>
    <p class="description lead"><%= t('home.contact.description') %></p>
  </div>
  <%# Form to ensure that the user can enter details in order to get in contact. %>   
  <%= form_tag request_contact_path, method: 'post', class: "contact-form pt-4" do %>
    <%= label_tag :name, t('home.contact.enter_name'), class: "contact-label"%>
    <%= text_field_tag :name, '', title: t('home.contact.enter_name'), size: 50, class: "contact-input", placeholder: t('home.contact.req'), required: true %>
    <hr class="no-pointer">
    <%= label_tag :email, t('home.contact.enter_email'), class: "contact-label"%>
    <%= email_field_tag :email, '', title: t('home.contact.enter_email'), class: "contact-input", placeholder: t('home.contact.req'), required: true %>
    <hr class="no-pointer">
    <%= label_tag :telephone, t('home.contact.enter_telephone'), class: "contact-label"%>
    <%= telephone_field_tag :telephone, '', title: t('home.contact.enter_telephone'), class: "contact-input", placeholder: t('home.contact.req'), required: true %>
    <hr class="no-pointer">
    <%= label_tag :message, t('home.contact.enter_message'), class: "contact-label"%>
    <%= text_area_tag :message, '', title: t('home.contact.enter_message'), rows: 5, class: "contact-input", placeholder: t('home.contact.req'), required: true %>
    <hr class="no-pointer">
    <%= submit_tag t('home.contact.submit'), class: "glow-shadow-2 btn btn-outline-info"%>
  <% end %>
</div>

app/views/home/index.html.erb
<%# Bootstrap jumbotron used in order to center the content in the center of the screen.  %>
<%# Responsive using bootstrap responsive classes %>
<div class="jumbotron col-lg-6 col-md-10 col-sm-12 col-xs-12 offset-md-1 offset-lg-3 float-md-center my-4">
    <div class="container">
        <h1 class="display-4 no-pointer"><%= t('home.title') %></h1>
        <p class="lead no-pointer"><%= t('home.welcome_message') %></p>
        <hr class="my-4 no-pointer">
        <%= link_to t('home.call_to_action'), films_path, class: 'btn btn-lg btn-outline-info mx-2 my-2 my-lg-0' %>
    </div>
</div>