config/routes.rb
Rails.application.routes.draw do
  resources :showings, except: [:new, :create, :edit, :update, :destroy]
  resources :bookings, except: [:show, :edit, :update, :index]
  resources :films, except: [:new, :create, :edit, :update, :destroy]
  resources :venues, only: [:index]
  root 'home#index'
  get 'film', to: "films#index"
  get 'showings', to: 'showings#index'
  get 'mybookings', to: 'my_bookings#index'
  get 'mybookings/find', to: "my_bookings#find"
  post 'book', to: "bookings#parseAjax"
  get 'contact', to: "home#contact"
  post 'request_contact', to: 'home#request_contact'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/venue.rb
class Venue < ApplicationRecord
    # Venue has many showings (Many to one)
    has_many :showings, dependent: :destroy
    # Name cannot be null and must be unique
    validates :name, presence: true, uniqueness: true
    # Row must not be null, nit be within 1 and 50
    validates :rows, presence: true, inclusion: {in: 1..50}
    # seats must not be null, nit be within 1 and 50
    validates :seats_per_row, presence: true, inclusion: {in: 1..50}
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  # Method to get all unique venues for a particular selected film
  # Param - film id
  def index 
    # Validation to esnure id parameter is present 
    if params[:film].present?
      # Validation to ensure that film id parameter is valid
      if Film.exists?(params[:film])
        @film = Film.find(params[:film])
        # Get a list of all unique venues for a particular film id 
        uniqueVenue_ids = Showing.where(film: params[:film]).pluck(:venue_id).uniq
        @uniqueVenues = Venue.find(uniqueVenue_ids)  
      else
        # If not valid redirect to film url with alert
        redirect_to films_url
        flash[:alert] = t("venues.index.no_param")
      end 
    else
      #If not present then redirect to root url with notice
      redirect_to root_url
      flash[:alert] = t("venues.index.bad_param")
    end 
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def venue_params
      params.require(:venue).permit(:name, :location, :image_url, :rows, :seats_per_row)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/index.html.erb
<%# Wrapper to ensure that the website isnt full viewport wodth on larger displays %>
<div class="wrapper-inner px-4">
  <div class="heading mx-2 mb-4">
    <h1 class="title display-4"><%= t('venues.index.title') %><%= @film.title %></h1>
    <p class="description lead"><%= t('venues.index.description') %></p>
  </div>

  <%# Grid to show each unique for a particular film %>
  <div class='item-grid mx-2 py-4'>
    <% @uniqueVenues.each do |venue|%>
    <%= link_to showings_path params: {venue: venue, film: @film} do %>
      <div class = "grid-cell" id="grid-item-<%= venue.id %>" onmouseenter="cellFade(true,this.id)" onmouseout="cellFade(false)" >
        <div id="grid-thumb-<%= venue.id %>" onclick="toggleExpand(true,this.id,'showing-expand')">
          <img class="grid-thumb no-pointer glow-shadow" src="<%= venue.image_url %>" />
          <h1 class='lead no-pointer m-2'><%= venue.name %></h1>     
        </div>
    </div>
    <% end %>            
<% end %>   
  </div>
</div>